SELECT * FROM FUNCIONARIOS;

SELECT COUNT(*) FROM FUNCIONARIOS;

SELECT COUNT(*) FROM FUNCIONARIOS WHERE SALARIO > 1000 AND DEPARTAMENTO = 'ESTAGIARIO';

SELECT SUM(SALARIO) FROM FUNCIONARIOS;

SELECT SUM(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ESTAGIARIO';

SELECT AVG(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ESTAGIARIO';

SELECT MAX(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ESTAGIARIO';

SELECT MIN(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ESTAGIARIO';

SELECT DEPARTAMENTO FROM FUNCIONARIOS;

SELECT DISTINCT(DEPARTAMENTO) FROM funcionarios;

SELECT * FROM FUNCIONARIOS ORDER BY NOME;
SELECT * FROM FUNCIONARIOS ORDER BY NOME DESC;

SELECT * FROM FUNCIONARIOS ORDER BY DEPARTAMENTO, SALARIO;
SELECT * FROM FUNCIONARIOS ORDER BY DEPARTAMENTO DESC, SALARIO DESC;

SELECT * FROM FUNCIONARIOS LIMIT 2;

SELECT * FROM FUNCIONARIOS LIMIT 1, 2;

SELECT AVG(SALARIO) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ESTAGIARIO';

SELECT DEPARTAMENTO, AVG(SALARIO) FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;
SELECT DEPARTAMENTO, AVG(SALARIO) FROM FUNCIONARIOS GROUP BY DEPARTAMENTO HAVING AVG(SALARIO)> 2000;


SELECT DEPARTAMENTO, AVG(SALARIO) FROM FUNCIONARIOS GROUP BY DEPARTAMENTO;
SELECT NOME FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'ESTAGIARIO';

SELECT NOME FROM FUNCIONARIOS WHERE DEPARTAMENTO IN ('ANALISTA JUNIOR');

SELECT NOME FROM FUNCIONARIOS WHERE DEPARTAMENTO IN (SELECT DEPARTAMENTO FROM FUNCIONARIOS GROUP BY DEPARTAMENTO HAVING AVG(SALARIO)> 2000);