SELECT * FROM FUNCIONARIOS;
SELECT * FROM VEICULOS;

SELECT * FROM FUNCIONARIOS INNER JOIN VEICULOS ON VEICULOS.FUNCIONARIO_ID = FUNCIONARIOS.ID;
SELECT * FROM FUNCIONARIOS F INNER JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

SELECT * FROM FUNCIONARIOS F LEFT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;
SELECT * FROM FUNCIONARIOS F RIGHT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

SELECT * FROM FUNCIONARIOS F LEFT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID
UNION
SELECT * FROM FUNCIONARIOS F RIGHT JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID;

INSERT INTO VEICULOS (FUNCIONARIO_ID, VEICULO, PLACA) VALUES (NULL, 'MOTO', 'SB-0003');

CREATE TABLE CPFS 
(
	ID INT UNSIGNED NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_CPF FOREIGN KEY (ID) REFERENCES FUNCIONARIOS (ID)
);

INSERT INTO CPFS (ID, CPF) VALUES (1, '111.111.111-11');
INSERT INTO CPFS (ID, CPF) VALUES (2, '222.111.111-11');
INSERT INTO CPFS (ID, CPF) VALUES (3, '333.111.111-11');
INSERT INTO CPFS (ID, CPF) VALUES (4, '444.111.111-11');
INSERT INTO CPFS (ID, CPF) VALUES (5, '555.111.111-11');

SELECT * FROM CPFS;

SELECT * FROM FUNCIONARIOS INNER JOIN CPFS ON FUNCIONARIOS.ID = CPFS.ID;
SELECT * FROM FUNCIONARIOS INNER JOIN CPFS USING(ID);

CREATE TABLE CLIENTES 
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    QUEM_INDICOU INT UNSIGNED,
    PRIMARY KEY (ID),
    CONSTRAINT FK_QUEM_INDICOU FOREIGN KEY (QUEM_INDICOU) REFERENCES CLIENTES (ID)
);

INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (1, 'ANDRÉ', NULL);
INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (2, 'ANDRÉ', 1);
INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (3, 'ANDRÉ', 2);
INSERT INTO CLIENTES (ID, NOME, QUEM_INDICOU) VALUES (4, 'ANDRÉ', 1);

UPDATE CLIENTES SET NOME = 'RAFAEL' WHERE ID = 4;

SELECT * FROM CLIENTES;

SELECT A.NOME AS CLIENTE, B.NOME AS INDICACAO FROM CLIENTES A JOIN CLIENTES B ON A.QUEM_INDICOU = B.ID;

SELECT * FROM FUNCIONARIOS F 
INNER JOIN VEICULOS V ON V.FUNCIONARIO_ID = F.ID
INNER JOIN CPFS ON CPFS.ID = F.ID;

CREATE VIEW FUNCIONARIOS_A AS SELECT * FROM FUNCIONARIOS WHERE SALARIO >= 4000;

SELECT * FROM FUNCIONARIOS_A;
UPDATE FUNCIONARIOS SET SALARIO = 4800 WHERE ID = 3;

DROP VIEW FUNCIONARIOS_A;