INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO, DEPARTAMENTO) VALUES (1, 'FERNANDO', 1400, 'TI');
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO, DEPARTAMENTO) VALUES (2, 'GUILHERME', 2500, 'ANALISTA JUNIOR');
INSERT INTO FUNCIONARIOS (NOME, SALARIO, DEPARTAMENTO) VALUES ('FABIO', 3700, 'ANALISTA PLENO');
INSERT INTO FUNCIONARIOS (ID, NOME, SALARIO, DEPARTAMENTO) VALUES (4, 'ANA', 6300, 'GERENTE');
INSERT INTO FUNCIONARIOS (NOME, SALARIO, DEPARTAMENTO) VALUES ('DOUGLAS', 1400, 'ESTAGIARIO');

SELECT * FROM FUNCIONARIOS;
SELECT * FROM FUNCIONARIOS WHERE SALARIO > 2000;
SELECT * FROM FUNCIONARIOS WHERE ID = 2;

UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.1 WHERE ID = 1;

UPDATE FUNCIONARIOS SET DEPARTAMENTO = 'ESTAGIARIO' WHERE ID = 1;

SET SQL_SAFE_UPDATES = 0;
/* SET SQL_SAFE_UPDATES = 1; */
UPDATE FUNCIONARIOS SET SALARIO = SALARIO * 1.1;

UPDATE FUNCIONARIOS SET SALARIO = ROUND(SALARIO * 1.1, 2);

DELETE FROM FUNCIONARIOS WHERE ID = 4;

INSERT INTO VEICULOS (FUNCIONARIO_ID, VEICULO, PLACA) VALUES (1, 'CARRO', 'SB-0001');
INSERT INTO VEICULOS (FUNCIONARIO_ID, VEICULO, PLACA) VALUES (1, 'CARRO', 'SB-0002');

SELECT * FROM VEICULOS;

UPDATE VEICULOS SET FUNCIONARIO_ID = 5 WHERE ID = 2;
UPDATE VEICULOS SET VEICULO = 'CAMINHAO' WHERE ID = 2;

INSERT INTO SALARIOS (FAIXA, INICIO, FIM) VALUES ('ESTAGIARIO', 1000, 2000);
INSERT INTO SALARIOS (FAIXA, INICIO, FIM) VALUES ('ANALISTA JUNIOR', 2500, 3500);
INSERT INTO SALARIOS (FAIXA, INICIO, FIM) VALUES ('ANALISTA PLENO', 4000, 5000);
INSERT INTO SALARIOS (FAIXA, INICIO, FIM) VALUES ('ANALISTA PLENO', 4000, 5000);

SELECT * FROM SALARIOS;
SELECT * FROM FUNCIONARIOS F WHERE SALARIO > 3000;
SELECT NOME, SALARIO FROM FUNCIONARIOS F WHERE F.SALARIO > 3000;
SELECT NOME AS 'FUNCIONARIO', SALARIO FROM FUNCIONARIOS F WHERE F.SALARIO > 3000;

SELECT * FROM FUNCIONARIOS WHERE NOME = 'GUILHERME'
UNION
SELECT * FROM FUNCIONARIOS WHERE ID = 5;

SELECT * FROM FUNCIONARIOS WHERE NOME = 'GUILHERME'
UNION ALL
SELECT * FROM FUNCIONARIOS WHERE NOME = 'GUILHERME';