CREATE DATABASE CURSO_SQL;

USE CURSO_SQL;
CREATE TABLE FUNCIONARIOS
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    SALARIO DOUBLE NOT NULL DEFAULT '0',
    DEPARTAMENTO  VARCHAR(45) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE VEICULOS 
(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FUNCIONARIO_ID INT UNSIGNED DEFAULT NULL,
    VEICULO VARCHAR(45) NOT NULL DEFAULT '',
    PLACA VARCHAR(10) NOT NULL DEFAULT '',
    PRIMARY KEY (ID),
    CONSTRAINT FK_VEICULOS_FUNCIONARIOS FOREIGN KEY (FUNCIONARIO_ID) REFERENCES FUNCIONARIOS (ID)
);

CREATE TABLE SALARIOS
(
	FAIXA VARCHAR(45) NOT NULL,
    INICIO DOUBLE NOT NULL,
    FIM DOUBLE NOT NULL,
    PRIMARY KEY (FAIXA)
);

ALTER TABLE FUNCIONARIOS CHANGE COLUMN NOME  NOME_FUNC VARCHAR (50) NOT NULL;
ALTER TABLE FUNCIONARIOS CHANGE COLUMN NOME_FUNC NOME VARCHAR (45) NOT NULL;

DROP TABLE SALARIOS;

CREATE INDEX DEPARTAMENTOS ON FUNCIONARIOS (DEPARTAMENTO);
CREATE INDEX NOMES ON FUNCIONARIOS (NOME(6));

CREATE TABLE ACESSORIOS (
  ID INT UNSIGNED NOT NULL,
  VALOR DOUBLE NOT NULL DEFAULT '0',
  FORNECEDOR VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE EMBLEMAS (
  ID INT NOT NULL,
  FORNECEDOR VARCHAR(45) NULL,
  EMBLEMA VARCHAR(10) NOT NULL,
  VALOR DOUBLE NOT NULL DEFAULT '0',
  PRIMARY KEY (ID)
);


